### ISSUE TITLE
Bad download link for specific versions

### ISSUE THREAD

**Issue by airadier** [jandelgado/gcov2lcov-action#11]
When a gcov2lcov version is specified (i.e. v1.0.4), the download link is created as:

https://github.com/jandelgado/gcov2lcov/releases/v1.0.4/download/gcov2lcov-linux-amd64.tar.gz

But it should be:

https://github.com/jandelgado/gcov2lcov/releases/download/v1.0.4/gcov2lcov-linux-amd64.tar.gz

It seems that for latest, it works as:

https://github.com/jandelgado/gcov2lcov/releases/latest/download/gcov2lcov-linux-amd64.tar.gz

But not for specific versions.

**Comment by jandelgado** [comment]
indeed, this is a bug and the download links are not constructed consistently. I fixed it, it should work now. @airadier, You can try it by testing the action with the commit-hash:

```yaml  
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@f39cf324554c178f3fd58cb2a7414e48a9181a48
```
