### ISSUE TITLE
gcov2lcov v1.1.0 naming format breaks old versions. 

### ISSUE THREAD

**Issue by Haegi** [jandelgado/gcov2lcov-action#17]
When specifying `jandelgado/gcov2lcov-action@v1.0.9` in github actions, it breaks since the release of `v1.1.0` because [defaults to the latest release](https://github.com/jandelgado/gcov2lcov/releases/latest/download), which has a new naming format.

Unfortunately, it breaks all of our pipelines and requires bumping all of them to use  `jandelgado/gcov2lcov-action@v1.1.0`.
Possible options to fix it would be revert the renaming and create a backwards compatible version of `gcov2lcov-action` or to re-release `gcov2lcov-action@v1.0.9` with backwards compatibility or a fixed version instead of using latest.
But note that `gcov2lcov-action@v1.0.9` would fail with a custom version input starting from `v1.1.0` as well.

**Comment by jandelgado** [comment]
I'll check if it's possible to provide a "legacy" binary. Is it possible for you to just use "v1" as the version tag? This will ensure that you use the most recent v1 version.

**Comment by jandelgado** [comment]
I fixed the `gcov2lcov` pipleline to include an artifact as expected by older versions of the action. Does it work for you, @Haegi ?

**Comment by Haegi** [comment]
Thanks @jandelgado! It works with `v1.0.9` & `v1.1.1` but we will migrate to `v1` soon to always get the most recent version.
- `v1.0.9` ✅ 
- `v1.1.0` :x:
  - Two matches and therefore fails. `PACKAGE_URL='https://github.com/jandelgado/gcov2lcov/releases/download/v1.1.1/gcov2lcov-linux-amd64.tar.gz
https://github.com/jandelgado/gcov2lcov/releases/download/v1.1.1/gcov2lcov_1.1.1_linux_amd64.tar.gz'` 
- `v1.1.1` ✅

**Comment by jandelgado** [comment]
Yes, the problem with 1.1.0 could not be fixed, therefore I recalled this release. Sorry for any inconvenience. But all other versions should be compatible now.

**Comment by Haegi** [comment]
No worries and thanks for the fast support.
