### ISSUE TITLE
Why not use precompiled binary?

### ISSUE THREAD

**Issue by septs** [jandelgado/gcov2lcov-action#5]
![image](https://user-images.githubusercontent.com/3842474/93716228-34a8b700-fba1-11ea-8530-37534dfb38e2.png)

like https://github.com/golangci/golangci-lint-action

from https://github.com/linxGnu/gosmpp/runs/1140698513

**Comment by jandelgado** [comment]
I'm not sure why you proposing the change. Is it to make sure that the correct version of `gcov2lcov` is used?

**Comment by septs** [comment]
gh-actions run docker very slower.

**Comment by septs** [comment]
gh-actions per run job will build docker image.

the a process need ≈ 20s to 30s

direct use precompiled binary, in gh-actions expected in 5s.

**Comment by jandelgado** [comment]
implemented with release 1.0.4

**Comment by jandelgado** [comment]
can we close the issue, @septs ?

**Comment by septs** [comment]
why docker based?

**Comment by jandelgado** [comment]
gcov2lcov needs installed go tooling available. Therefore a container. Feel free to Open a MR for further improvents - thanks
